name: CD Fake
on: 
    workflow_dispatch:
jobs:
    deploy-fake-homologacao:
        environment: homologacao
        runs-on: ubuntu-latest
        steps:
          - name: Fake de deploy em ambiente
            run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
    deploy-fake-producao:
      needs: [deploy-fake-homologacao]
      environment: producao
      runs-on: ubuntu-latest
      steps:
          - name: Fake de deploy em ambiente
            run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
