name: CD Fake
on: 
    workflow_dispatch:
        inputs:
          ambiente:
            type: choice
            options:
              - homologacao
              - producao
jobs:
    deploy-fake:
        environment: ${{ inputs.ambiente }}
        runs-on: ubuntu-latest
        steps:
            - name: Fake de deploy em ambiente
              run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"